services:
  resawod:
    build: .
    image: resawod_nubapp
    container_name: resawod
    volumes:
      - ./path/to/data:/data
    environment:
      - DEV_MODE=0
    logging:
      options:
        max-size: "50m"
    restart: none